# Generated by Django 3.2.1 on 2021-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosakata', '0003_alter_kosakata_arti_kata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosakata',
            name='arti_kata',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
